config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#dashboard'
  get 'download_cms', to: 'home#download_cms'
  get 'download_auth', to: 'home#download_auth'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def dashboard
  end

  def download_cms
    @filename = "/home/harissh/Documents/DB/api-2018_db/CMS_DB.sql"
    send_file(@filename, :filename => "CMS_DB.sql")
  end

  def download_auth
    @filename = "/home/harissh/Documents/DB/central-authentication_db/AUTH_DB.sql"
    send_file(@filename, :filename => "AUTH_DB.sql")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/dashboard.html.erb
<br>
<div class="text-md-center">
  <h1>DATABASE DOWNLOAD</h1>
</div>
<br>
<br>
<div class="text-md-center">
  <%= link_to "Download CMS (api-2018) DB", download_cms_path, class: "btn btn-primary" %>
</div>
<br>
<div class="text-md-center">
  <%= link_to "Download Central-Authentication DB", download_auth_path, class: "btn btn-success" %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DB Download</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
<%= yield %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>